### ISSUE TITLE
[FEATURE] Add support for authentication

### ISSUE THREAD

**Issue by ommarmol** [idealista/redis_role#106]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filled: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aidealista
    * Checked that there is not already provided the described functionality

### Description

It would be great if some mechanism for authentication were provided, such as the [requirepass](https://redis.io/docs/management/security/) option in the _redis.conf_ file.

**Expected behavior:** I expect to be able to configure password authentication when deploying a redis server using this role.
**Actual behavior:** The Redis server is always deployed without authentication.

### Versions

All

**Comment by santi-eidu** [comment]
Auth must be mandatory.
